apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lectern-data
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lectern-backups
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
